export const states = [
    {
        "name":"Schleswig-Holstein",
        "code":"SH"
    },
    {
        "name":"Hamburg",
        "code":"HH"
    },
    {
        "name":"Niedersachsen",
        "code":"NI"
    },
    {
        "name":"Bremen",
        "code":"HB"
    },
    {
        "name":"Nordrhein-Westfalen",
        "code":"NW"
    },
    {
        "name":"Hessen",
        "code":"HE"
    },
    {
        "name":"Rheinland-Pfalz",
        "code":"RP"
    },
    {
        "name":"Baden-Württemberg",
        "code":"BW"
    },
    {
        "name":"Bayern",
        "code":"BY"
    },
    {
        "name":"Saarland",
        "code":"SL"
    },
    {
        "name":"Berlin",
        "code":"BE"
    },
    {
        "name":"Brandenburg",
        "code":"BB"
    },
    {
        "name":"Mecklenburg-Vorpommern",
        "code":"MV"
    },
    {
        "name":"Sachsen",
        "code":"SN"
    },
    {
        "name":"Sachsen-Anhalt",
        "code":"ST"
    },
    {
        "name":"Thüringen",
        "code":"TH"
    }
];